name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build My App
        run: |
          # البحث عن مكان ملف المشروع الحقيقي
          PROJECT_ROOT=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          echo "Found project at: $PROJECT_ROOT"
          cd "$PROJECT_ROOT"
          flutter pub get
          flutter build apk --debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: My-Noor-App
          path: "**/*.apk"
